name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: src/git-bundle-server

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'src/git-bundle-server/go.mod'

      - name: Build
        run: make -C src/git-bundle-server build

      - name: Check style
        run: make -C src/git-bundle-server vet

      - name: Run unit tests
        run: make -C src/git-bundle-server test
